Add kotlin SDK
boticord/docs-v3 pull request #14
Opened 2023-06-09 10:32 UTC by MagM1go

Добавлена информация о библиотеке botikotlin

Язык: Kotlin
Библиотека: botikotlin

Простая для использования библиотека, созданная для упрощения взаимодействия с BotiCord API v3

[Примеры можно найти тут](https://github.com/MagM1go/botikotlin/tree/main/examples)

Ссылка на документацию: https://magmigo2.gitbook.io/boticord-kotlin/

Ссылка на репозиторий: https://github.com/MagM1go/botikotlin

Ссылка на автора: https://github.com/MagM1go

2023-06-09 13:53 UTC, everydayrains requested changes
Нужны простые примеры либы (отправка статистики и тп), а не редирект на свои доки.

2023-06-09 14:04 UTC, Mirdukkk commented
В нашей документации должны быть расположены хотя-бы какие-то примеры и как оно должно работать. Вот, например: https://docs.boticord.top/libraries/boticordjs/

2023-06-09 14:04 UTC, Mirdukkk commented
Нельзя просто отправить всё в сторонние доки

2023-06-09 14:05 UTC, MagM1go commented
а. Ну, сейчас добавлю. Просто смотрю, а у boticordpy и js нет там ничего, думаю, а в чём мем.
Сейчас добавлю

2023-06-09 14:06 UTC, Mirdukkk commented
Там вообще страницы пустые потому что разработчики ещё ничего не сделали под V3

2023-06-09 14:07 UTC, everydayrains commented
Обнови форк еще.

2023-06-09 14:07 UTC, MagM1go commented
обновлю

2023-06-09 14:17 UTC, everydayrains commented
А так же, добавь возможность сменить апи урл в опциях клиента, не думаю что это сложно будет сделать. Для тестов сейчас, да и в будущее на всякий.

2023-06-09 14:19 UTC, MagM1go commented
Наверное завтра это сделаю, сейчас я уже не за пк буду, доки отправляю и фсё

2023-06-09 14:20 UTC, everydayrains commented on docs/sdk/kotlin.mdx
> +[Репозиторий](https://github.com/MagM1go/botikotlin/)
К нам не будешь переносить? Или оставишь у себя

2023-06-09 14:21 UTC, MagM1go commented on docs/sdk/kotlin.mdx
> +[Репозиторий](https://github.com/MagM1go/botikotlin/)
Перенесу, только завтра уже наверное 👌🏻

2023-06-09 23:41 UTC, everydayrains commented
@MagM1go вопрос на засыпку. Оно дружит с java? Оказывается есть уже либа для в1 на Джаве @boticord/library-developer-java

2023-06-09 23:59 UTC, MagM1go commented
> @MagM1go вопрос на засыпку. Оно дружит с java? Оказывается есть уже либа для в1 на Джаве @boticord/library-developer-java

С джавой оно не дружит. Но джава либа на котлине будет работать

2023-06-10 02:55 UTC, MagM1go commented
А, стоп. С переносом немного повременить. Там jitpack зависит от репозитория гитхаба, наверное пока не буду переносить

2023-06-10 08:24 UTC, everydayrains commented
> А, стоп. С переносом немного повременить. Там jitpack зависит от репозитория гитхаба, наверное пока не буду переносить 

А что мешает перенести репо и настроить её потом?

2023-06-10 08:47 UTC, megoRU commented
Зачем Котлин когда есть джава?

2023-06-10 09:14 UTC, MagM1go commented
> > А, стоп. С переносом немного повременить. Там jitpack зависит от репозитория гитхаба, наверное пока не буду переносить
> 
> А что мешает перенести репо и настроить её потом?

Ничего, вроде, но в принципе разницы не будет /shrug

2023-06-10 09:14 UTC, MagM1go commented
> Зачем Котлин когда есть джава? Опять делать велосипед?

а почему бы и нет?

2023-06-10 09:16 UTC, schizocipherka commented
4:19
> Зачем Котлин когда есть джава? Опять делать велосипед?

4:20
> > @MagM1go вопрос на засыпку. Оно дружит с java? Оказывается есть уже либа для в1 на Джаве @boticord/library-developer-java
> 
> С джавой оно не дружит. Но джава либа на котлине будет работать

2023-06-10 09:21 UTC, everydayrains commented
Экспертные гении, расскажите в чем преимущество либы именно на kt, которая только для kt. 
Если на java оно работает в обе стороны. В чем тогда проблема что её поставить в Котлин проект?

2023-06-10 09:25 UTC, MagM1go commented
> Экспертные гении, расскажите в чем преимущество либы именно на kt, которая только для kt. Если на java оно работает в обе стороны. В чем тогда проблема что её поставить в Котлин проект?

Преимуществ в этом плане, захотелось - сделал. Иногда и по несколько либ на одном языке пишут, а тут из-за того, что язык работает также, как и другой, но в другой обёртке, обозлились

2023-06-10 09:30 UTC, EveryDayRains commented
В общем, ждем когда будет сделан реврайт для джавы, а там посмотрим.

2023-06-10 09:32 UTC, MagM1go commented
> В общем, ждем когда будет сделан реврайт для джавы, а там посмотрим.

а зОчем ждать, когда можно не ждать, что изменится то

2023-06-10 09:34 UTC, SaphirePI commented
Я только одного не понял, почему Ливиксу на это не похуй) Человек добавил свою либу, в чем проблема?

2023-06-10 09:37 UTC, schizocipherka commented
> Я только одного не понял, почему Ливиксу на это не похуй) Человек добавил свою либу, в чем проблема?

![image](https://github.com/boticord/docs-v3/assets/32297717/dcae9f6c-e7e5-48a1-880e-0172f394af25)

2023-06-10 12:06 UTC, Mirdukkk commented
> Экспертные гении, расскажите в чем преимущество либы именно на kt, которая только для kt. Если на java оно работает в обе стороны. В чем тогда проблема что её поставить в Котлин проект?

я как экспертный гений, говорю что на жаве уже почти ничё нового не пишут, только на котле. это как с тайпскриптом - если проект новый, скорее всего он будет на тс. поэтому либа чисто под котлин вполне себе имеет право на существование в рамках не особо крупного ботикорда, а вот JDA не имеет права юзать котлин из-за кучи легаси на нём.
да и вообще, либа уже готова, принимаем и всё. зачем это обсуждение?

2023-06-10 13:34 UTC, MagM1go commented
> @MagM1go сделай не `devApiUrl: Boolean` а строку для указания домена. Не обязательно дев домен может быть как сейчас у нас.

ну вроде изменил, доки ща поправлю в этом моменте

2023-06-10 13:42 UTC, MagM1go commented
изменил

2023-06-10 13:46 UTC, EveryDayRains commented
> изменил

обновляй доки и переноси либо на оргу бк

2023-06-10 13:46 UTC, MagM1go commented
переносить ж необязательно

2023-06-10 13:47 UTC, MagM1go commented
доки я обновил уже, ctrl f5

2023-06-10 13:47 UTC, MagM1go commented
> доки я обновил уже, ctrl f5

а, ну примечание лишь могу добавить на время до релиза бкв2

2023-06-10 14:21 UTC, EveryDayRains commented
> переносить ж необязательно

желательно

2023-06-10 14:28 UTC, MagM1go commented
та уже лежит там на джаве, на мою, кто захотят, через доки апишки перейдут. Это ж желательно

2023-06-10 14:30 UTC, EveryDayRains approved these changes

2023-06-10 14:30 UTC, merged